import os

# The decky plugin module is located at decky-loader/plugin
# For easy intellisense checkout the decky-loader code repo
# and add the `decky-loader/plugin/imports` path to `python.analysis.extraPaths` in `.vscode/settings.json`
import decky
import asyncio
from settings import SettingsManager
import logging

RESOLVED_DNS_CONFIG_PATH="/etc/systemd/resolved.conf.d/decky-dot-dns.conf"
SETTINGS_DIR = os.environ["DECKY_PLUGIN_SETTINGS_DIR"]

DNS_PRESETS = {
    "None": {
        "insecure_dns": "",
        "secure_dns": "",
        "insecure_dnsv6": "",
        "secure_dnsv6": "",
        "use_dot": False
    },
    "CloudFlare": {
        "insecure_dns": "1.1.1.1",
        "secure_dns": "cloudflare-dns.com",
        "insecure_dnsv6": "2606:4700:4700::1111",
        "secure_dnsv6": "cloudflare-dns.com",
        "use_dot": True
    },
    "Google": {
        "insecure_dns": "8.8.8.8",
        "secure_dns": "dns.google",
        "insecure_dnsv6": "2001:4860:4860::8888",
        "secure_dnsv6": "dns.google",
        "use_dot": True    
    },
    "dns0.eu": {
        "insecure_dns": "193.110.81.0",
        "secure_dns": "dns0.eu",
        "insecure_dnsv6": "2a0f:fc80::",
        "secure_dnsv6": "dns0.eu",
        "use_dot": True    
    },
    "Quad9": {
        "insecure_dns": "9.9.9.10",
        "secure_dns": "dns10.quad9.net",
        "insecure_dnsv6": "2620:fe::10",
        "secure_dnsv6": "dns10.quad9.net",
        "use_dot": True    
    }
}

class Plugin:
    SettingsManager = SettingsManager(SETTINGS_DIR, "settings.json")
    
    async def push_custom_dns_override(self, insecure_dns: str, secure_dns: str, insecure_dnsv6: str, secure_dnsv6: str, use_dot: bool = False):
        logging.info(f"Pushing custom dns override: insecure_dns={insecure_dns}, secure_dns={secure_dns}, insecure_dnsv6={insecure_dnsv6}, secure_dnsv6={secure_dnsv6}, use_dot={use_dot}")
        try:
            # Ensure that the path exists
            os.makedirs(os.path.dirname(RESOLVED_DNS_CONFIG_PATH), exist_ok=True)

            dns_string = f"{insecure_dns}" + (f"#{secure_dns}" if use_dot else "")
            dns_string = f"{dns_string} {insecure_dnsv6}" + (f"#{secure_dnsv6}" if use_dot else "")
            file_content = f"""# Generated by decky-dot-dns
[Resolve]
DNS={dns_string}
DNSOverTLS={"yes" if use_dot else "no"}
"""        
            with open(RESOLVED_DNS_CONFIG_PATH, "w") as f:
                f.write(file_content)

            self.SettingsManager.setSetting("insecure_dns", insecure_dns)
            self.SettingsManager.setSetting("secure_dns", secure_dns)
            self.SettingsManager.setSetting("insecure_dnsv6", insecure_dnsv6)
            self.SettingsManager.setSetting("secure_dnsv6", secure_dnsv6)
            self.SettingsManager.setSetting("use_dot", use_dot)
            
            logging.info(f"Pushed custom dns override: {file_content}")
            await self.restart_resolved()
        except Exception as e:
            logging.error(f"Failed to push custom dns override: {e}")

    async def apply_dns_preset(self, preset: str):
        if preset not in DNS_PRESETS:
            logging.error(f"Invalid dns preset: {preset}")
            return
        if preset == "None":
            await self.drop_custom_dns_override()
            return
        logging.info(f"Applying dns preset: {preset}")
        await self.push_custom_dns_override(**DNS_PRESETS[preset])

    async def get_presets(self):
        return list(DNS_PRESETS.keys())

    async def drop_custom_dns_override(self):
        if os.path.exists(RESOLVED_DNS_CONFIG_PATH):
            os.remove(RESOLVED_DNS_CONFIG_PATH)
            logging.info(f"Removed custom dns override")
        else:
            logging.info(f"Custom dns override not found")

        await self.restart_resolved()

    async def restart_resolved(self):
        os.system("systemctl restart systemd-resolved")
        logging.info(f"Restarted systemd-resolved")

    async def get_dns_settings(self):
        return [
            self.SettingsManager.getSetting("insecure_dns"),
            self.SettingsManager.getSetting("secure_dns"),
            self.SettingsManager.getSetting("insecure_dnsv6"),
            self.SettingsManager.getSetting("secure_dnsv6"),
            self.SettingsManager.getSetting("use_dot")
        ]   

    async def _unload(self):
        pass

    async def _uninstall(self):
        await self.drop_custom_dns_override()
        await self.restart_resolved()
        pass

    async def _migration(self):
        pass